version: '3.3'

services:
  mongodb:
    image: mongo:6.0
    volumes:
      - ./.docker/mongodb:/data/db
    restart: always
    ports:
      - 27017:27017
    networks:
      - go-concepts
  
networks:
  go-concepts:
    driver: bridge